# -*- coding: utf-8 -*-
"""breast cancer machine learning project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182dpv4bhswnrO84yFMPcx_feLC-7OPXh
"""

import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Data Collection & Processing"""

#loading the data from saklearn
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

print(breast_cancer_dataset)

#loading the data towards a panda data frame
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns=breast_cancer_dataset.feature_names)

#print the first 5 rows of the dataset.
data_frame.head()

#adding the target column to the dataframe
data_frame['label']=breast_cancer_dataset.target

#printing the last 5 rows of the data frame here
data_frame.tail()

data_frame.shape

#getting some information about the data
data_frame.info()

#chechking for missing values
data_frame.isnull().sum()

#statistical messages about the data set
data_frame.describe()

#checking the distribution of the target variable
data_frame['label'].value_counts()

"""1->Benign
0->Malignant
"""

data_frame.groupby('label').mean()

"""Separating the features and target"""

x=data_frame.drop(columns='label')
y=data_frame['label']

print(x)

print(y)

"""Spilitting the data into training data and the testing data"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

print(x.shape,x_train.shape,x_test.shape)

"""Model training
(logistic regression model)
"""

model=LogisticRegression()

#training the logistic regression model using training data
model.fit(x_train,y_train)

"""Model evaluation(accuracy score)

"""

#accuracy on training data
x_train_prediction=model.predict(x_train)
training_data_accuracy=accuracy_score(y_train,x_train_prediction)

print('Accuracy on training data:',training_data_accuracy)

#accuracy on test data
x_test_prediction=model.predict(x_test)
test_data_accuracy=accuracy_score(y_test,x_test_prediction)

print("Accuracy on test data:",test_data_accuracy)

"""Building a predictive system"""

input_data=(11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,0.1052,0.2597,0.09744,0.4956,1.156,3.445,27.23,0.00911,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.5,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.173
)
#to change the input data to a numpy array
input_data_as_numpy_array=np.asarray(input_data)
#reshape the array as an predicting for one data point
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)
if(prediction[0]==0):
    print('The breast cancer is Malignant')
else:
    print('The breast cancer is Benign')